"""add attachment_url to decisions

Revision ID: 63732f8d1f19
Revises: f19688896ca7
Create Date: 2026-07-23 09:57:54.543513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63732f8d1f19'
down_revision: Union[str, Sequence[str], None] = 'f19688896ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('attachment_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'attachment_url')
    # ### end Alembic commands ###
