"""add reviewer assignments table and assigned reviewer to decisions

Revision ID: 75d3cf5246e8
Revises: 866dd26c47e7
Create Date: 2026-08-02 21:03:25.296073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d3cf5246e8'
down_revision: Union[str, Sequence[str], None] = '866dd26c47e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('assigned_reviewer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'decisions', 'users', ['assigned_reviewer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decisions', type_='foreignkey')
    op.drop_column('decisions', 'assigned_reviewer_id')
    # ### end Alembic commands ###
