"""add_meeting_note_to_enum

Revision ID: a66e2506a519
Revises: 4bbc23f5da41
Create Date: 2026-07-18 15:00:32.160985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a66e2506a519'
down_revision: Union[str, Sequence[str], None] = '4bbc23f5da41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE discussionmessagetype ADD VALUE 'meeting_note'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
