"""add ai_summary cache to decisions

Revision ID: e78d654418b7
Revises: 5d6f8e9e6c6b
Create Date: 2026-08-14 20:54:41.689659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e78d654418b7'
down_revision: Union[str, Sequence[str], None] = '5d6f8e9e6c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('decisions', sa.Column('ai_summary_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'ai_summary_updated_at')
    op.drop_column('decisions', 'ai_summary')
    # ### end Alembic commands ###
