"""empty message

Revision ID: eebf43d4ffba
Revises: e2034f9f3b9c
Create Date: 2026-07-16 17:21:14.258326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eebf43d4ffba'
down_revision: Union[str, Sequence[str], None] = 'e2034f9f3b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussion_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('comment', 'reply', name='discussionmessagetype'), nullable=False),
    sa.Column('attachment_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['discussion_messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussion_messages_decision_id'), 'discussion_messages', ['decision_id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_id'), 'discussion_messages', ['id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_parent_id'), 'discussion_messages', ['parent_id'], unique=False)
    op.create_index(op.f('ix_discussion_messages_user_id'), 'discussion_messages', ['user_id'], unique=False)
    op.drop_table('playing_with_neon')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    op.drop_index(op.f('ix_discussion_messages_user_id'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_parent_id'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_id'), table_name='discussion_messages')
    op.drop_index(op.f('ix_discussion_messages_decision_id'), table_name='discussion_messages')
    op.drop_table('discussion_messages')
    # ### end Alembic commands ###
