"""update_audit_log_schema

Revision ID: fc0f4741dcef
Revises: 9746f4fe09ea
Create Date: 2026-07-29 17:43:20.679191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0f4741dcef'
down_revision: Union[str, Sequence[str], None] = '9746f4fe09ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first to avoid integrity violation with existing rows
    op.add_column('audit_logs', sa.Column('log_type', sa.String(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE audit_logs SET log_type = 'activity'")
    
    # Alter column to be NOT NULL
    op.alter_column('audit_logs', 'log_type', nullable=False)
    
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_log_type'), 'audit_logs', ['log_type'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_log_type'), table_name='audit_logs')
    op.alter_column('audit_logs', 'entity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('audit_logs', 'log_type')
    # ### end Alembic commands ###
